spring:
  application:
    name: converseSphere
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: MysqlPass@2024
    url: jdbc:mysql://localhost:3306/converseSphere
server:
  port: 5454
    
